fos_user_group_list:
    path: /list
    defaults: { _controller: RestaurantBundle:Group:list }
    methods:  [GET]

fos_user_group_new:
    path: /new
    defaults: { _controller: RestaurantBundle:Group:new }
    methods:  [GET, POST]

fos_user_group_show:
    path: /{groupName}
    defaults: { _controller: RestaurantBundle:Group:show }
    methods:  [GET]

fos_user_group_edit:
    path: /{groupName}/edit
    defaults: { _controller: RestaurantBundle:Group:edit }
    methods:  [GET, POST]

fos_user_group_delete:
    path: /{groupName}/delete
    defaults: { _controller: RestaurantBundle:Group:delete }
    methods:  [GET]