fos_user_registration_register:
    path: /
    defaults: { _controller: RestaurantBundle:Registration:register }
    methods:  [POST, GET]

fos_user_registration_check_email:
    path: /check-email
    defaults: { _controller: RestaurantBundle:Registration:checkEmail }
    methods:  [GET]

fos_user_registration_confirm:
    path: /confirm/{token}
    defaults: { _controller: RestaurantBundle:Registration:confirm }
    methods:  [GET]

fos_user_registration_confirmed:
    path: /confirmed
    defaults: { _controller: RestaurantBundle:Registration:confirmed }
    methods:  [GET]