fos_user_resetting_request:
    path: /request
    defaults: { _controller: RestaurantBundle:Resetting:request }
    methods:  [GET]

fos_user_resetting_send_email:
    path: /send-email
    defaults: { _controller: RestaurantBundle:Resetting:sendEmail }
    methods:  [POST]

fos_user_resetting_check_email:
    path: /check-email
    defaults: { _controller: RestaurantBundle:Resetting:checkEmail }
    methods:  [GET]

fos_user_resetting_reset:
    path: /reset/{token}
    defaults: { _controller: RestaurantBundle:Resetting:reset }
    methods:  [GET, POST]