fos_user_security_login:
    path: /login
    defaults: { _controller: RestaurantBundle:Security:login }
    methods:  [POST, GET]

fos_user_security_check:
    path: /login_check
    defaults: { _controller: RestaurantBundle:Security:check }
    methods:  [POST]

fos_user_security_logout:
    path: /logout
    defaults: { _controller: RestaurantBundle:Security:logout }
    methods:  [GET]