<?php

namespace RestaurantBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CompanyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompanyRepository extends \Doctrine\ORM\EntityRepository
{
	public function getFilterCompany($name) {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('c')
                ->from('RestaurantBundle:Company', 'c');
        $qb->where('c.name like :name')
                ->setParameters(array('name'=>'%'.$name.'%'));
        $entites = $qb->getQuery()->getResult();
        return $entites;
    }
}
