<?php

namespace RestaurantBundle\Repository;

/**
 * ConciergeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConciergeRepository extends \Doctrine\ORM\EntityRepository
{
}
