<?php

namespace RestaurantBundle\Repository;

/**
 * CountryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CountryRepository extends \Doctrine\ORM\EntityRepository
{
    public function getFilterCountry($name) {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('c')
            ->from('RestaurantBundle:Country', 'c');
        $qb->where('c.name like :name')
            ->orWhere('c.indicatif like :name')
            ->setParameters(array('name'=>'%'.$name.'%'));
        $entites = $qb->getQuery()->getResult();
        return $entites;
    }
}
