<?php

namespace RestaurantBundle\Repository;

/**
 * CustomerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerRepository extends \Doctrine\ORM\EntityRepository
{
        public function getFilterCustomer($name) {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('c')
                ->from('RestaurantBundle:Customer', 'c');
        $qb->where('c.firstName like :firstName or c.lastName like :lastName')
                ->setParameters(array('firstName'=>'%'.$name.'%','lastName'=>'%'.$name.'%'));
        $entites = $qb->getQuery()->getResult();
        return $entites;
        }

        public function getAllCustomers()
        {
                $qb = $this->_em->createQueryBuilder();
                $qb->select('c')
                    ->from('RestaurantBundle:Customer', 'c');
                $qb->where('c.id > 1');
                $entites = $qb->getQuery()->getResult();
                return $entites;
        }
}
