<?php

namespace RestaurantBundle\Repository;

/**
 * CustomerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerRepository extends \Doctrine\ORM\EntityRepository
{
        public function getFilterCustomer($name) {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('c')
                ->from('RestaurantBundle:Customer', 'c');
        $qb->where('c.firstName like :firstName or c.lastName like :lastName')
                ->setParameters(array('firstName'=>'%'.$name.'%','lastName'=>'%'.$name.'%'));
        $entites = $qb->getQuery()->getResult();
        return $entites;
        }

        public function getAllCustomers($limit,$page)
        {
                $qb = $this->_em->createQueryBuilder();
                $qb->select('c')
                    ->from('RestaurantBundle:Customer', 'c');
                $qb->where('c.id > 1');
                $offset=$page*$limit;
                $entites = $qb->getQuery()->setMaxResults($limit)->setFirstResult($offset)->getResult();
                return $entites;
        }

        public function getCountCustomers(){
            $qb = $this->_em->createQueryBuilder();
            $qb->select('count(c.id)');
            $qb->from('RestaurantBundle:Customer','c');
            $count = $qb->getQuery()->getSingleScalarResult();
            return $count;
        }
}
