<?php

namespace RestaurantBundle\Repository;

/**
 * FloorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FloorRepository extends \Doctrine\ORM\EntityRepository
{
}
