<?php

namespace RestaurantBundle\Repository;

/**
 * GroupTablRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupTablRepository extends \Doctrine\ORM\EntityRepository
{
}
