<?php

namespace RestaurantBundle\Repository;

/**
 * NotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationRepository extends \Doctrine\ORM\EntityRepository
{
    public function Today()
    {
        $date=new \DateTime();
        $qb = $this->createQueryBuilder('u')  //add select and array for JSON
        ->where('u.createdAt LIKE :date')
            ->addOrderBy('u.createdAt','ASC')
            ->setParameter('date', $date->format("Y-m-d")."%")
            ->setMaxResults(50);

        return $qb->getQuery()->getResult();
    }
    public function Yesterday()
    {
        $date=new \DateTime("yesterday");
        $qb = $this->createQueryBuilder('u')  //add select and array for JSON
        ->where('u.createdAt LIKE :date')
            ->addOrderBy('u.createdAt','ASC')
            ->setParameter('date', $date->format("Y-m-d")."%")
            ->setMaxResults(50);

        return $qb->getQuery()->getResult();
    }
    public function ThisMonth()
    {
        $date=new \DateTime();
        $datetoday=new \DateTime();
        $dateyesterday=new \DateTime();
        $qb = $this->createQueryBuilder('u')  //add select and array for JSON
        ->where('u.createdAt LIKE :date')
            ->andWhere('u.createdAt NOT LIKE :datetoday')
            ->andWhere('u.createdAt NOT LIKE :dateyesterday')
            ->addOrderBy('u.createdAt','ASC')
            ->setParameter('date', $date->format("Y-m")."%")
            ->setParameter('datetoday', $datetoday->format("Y-m-d")."%")
            ->setParameter('dateyesterday', $dateyesterday->format("Y-m-d")."%")
            ->setMaxResults(50);

        return $qb->getQuery()->getResult();
    }
    public function AllLimited()
    {
        $date=new \DateTime();
        $qb = $this->createQueryBuilder('u')  //add select and array for JSON
            ->addOrderBy('u.createdAt','DESC')
            ->setMaxResults(20);

        return $qb->getQuery()->getResult();
    }
}
