<?php

namespace RestaurantBundle\Repository;

/**
 * OccasionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OccasionRepository extends \Doctrine\ORM\EntityRepository
{
}
