<?php

namespace RestaurantBundle\Repository;

/**
 * ServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceRepository extends \Doctrine\ORM\EntityRepository
{
	public function findAll()
    {
        return $this->findBy(array(), array('ordre' => 'ASC'));
    }
    public function findBetweenInterval($interval)
    {
        $qb = $this->createQueryBuilder('u')->where(':interval BETWEEN u.de AND u.a')->setParameter('interval', $interval);
        return $qb->getQuery()->getResult();
    }
}
