<?php

namespace RestaurantBundle\Repository;

/**
 * TablTypeTablRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TablTypeTablRepository extends \Doctrine\ORM\EntityRepository
{
}
