<?php

namespace RestaurantBundle\Repository;

/**
 * TablRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TablRepository extends \Doctrine\ORM\EntityRepository
{
}
