<?php

namespace RestaurantBundle\Repository;

/**
 * TypeTablRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeTablRepository extends \Doctrine\ORM\EntityRepository
{
}
