state_add_xhr:
    path: /add_xhr
    defaults: { _controller: RestaurantBundle:State:addXhr }
    methods:  [POST]
    options:
        expose: true

state_delete_xhr:
    path: /remove_xhr/{id}
    defaults: { _controller: RestaurantBundle:State:deleteXhr }
    methods:  [DELETE]
    options:
        expose: true
    requirements:
        id: \d+

state_edit_xhr:
    path: /edit_xhr/{id}
    defaults: { _controller: RestaurantBundle:State:editXhr }
    methods:  [POST]
    options:
        expose: true
    requirements:
        id: \d+